root = "."
tmp_dir = "tmp"

[build]
work_dir = "."
cmd = "go build -o \"./tmp/main\" ."
bin = "./tmp/main"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "client", "./client"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go", "client/.*", ".*/client/.*"]

[screen]
clear_on_rebuild = true
